GOOSE_CLI_THEME: dark
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: null
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  github:
    args:
    - -y
    - '@modelcontextprotocol/server-github'
    bundled: null
    cmd: npx
    description: null
    enabled: true
    env_keys:
    - GITHUB_PERSONAL_ACCESS_TOKEN
    envs: {}
    name: github
    timeout: 300
    type: stdio
OPENAI_BASE_PATH: v1/chat/completions
OPENAI_HOST: https://api.openai.com
GOOSE_PROVIDER: openai
OLLAMA_HOST: http://0.0.0.0:8080
GOOSE_MODEL: o4-mini
