OPENAI_BASE_PATH: v1/chat/completions
GOOSE_CLI_THEME: dark
extensions:
  anki-mcp:
    args:
    - --yes
    - anki-mcp-server
    bundled: null
    cmd: npx
    description: MCP server that connects to Anki
    enabled: true
    env_keys: []
    envs: {}
    name: anki-mcp
    timeout: 600
    type: stdio
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: null
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  github:
    args:
    - -y
    - '@modelcontextprotocol/server-github'
    bundled: null
    cmd: npx
    description: null
    enabled: true
    env_keys:
    - GITHUB_PERSONAL_ACCESS_TOKEN
    envs: {}
    name: github
    timeout: 300
    type: stdio
OLLAMA_HOST: http://0.0.0.0:8080
OPENAI_HOST: https://api.openai.com
GOOSE_PROVIDER: openai
GOOSE_MODEL: o4-mini
