model = "gpt-5.4"
service_tier = "fast"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[features]
codex_hooks = true


[mcp_servers.chrome_devtools]
command = "cmd"
args = [
    "/c",
    "npx",
    "-y",
    "chrome-devtools-mcp@latest",
    "--browserUrl",
    "http://127.0.0.1:9222"
]
enabled = true
